Itanio.SessaoAoVivo.WebUI.Frontend/Models/LoginViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using Itanio.SessaoAoVivo.Dominio;

namespace Itanio.SessaoAoVivo.WebUI.Frontend.Models
{
    public class LoginViewModel
    {
        [Required] public string Nome { get; set; }

        [Required] public string Cidade { get; set; }

        // [Required]
        public string Uf { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        //   [Required]
        //  [UIHint("Senha")]
        public string Senha { get; set; }

        public bool LembrarMe { get; set; }

        internal static Usuario ToEntity(LoginViewModel viewModel)
        {
            return new Usuario
            {
                Nome = viewModel.Nome,
                DataCriacao = DateTime.Now,
                Ativo = true,
                Cidade = viewModel.Cidade,
                Email = viewModel.Email,
                Senha = viewModel.Senha,
                UF = viewModel.Uf,
                Nick = viewModel.Email.Replace('@', '_').Replace('.', '_')
            };
        }
    }
}

Itanio.SessaoAoVivo.WebUI.Frontend/Controllers/AutenticacaoController.cs
using System.Web.Mvc;
using System.Web.Security;
using Carubbi.ServiceLocator;
using Itanio.SessaoAoVivo.Dominio;
using Itanio.SessaoAoVivo.ServicosAplicacao;
using Itanio.SessaoAoVivo.WebUI.Frontend.Models;

namespace Itanio.SessaoAoVivo.WebUI.Frontend.Controllers
{
    [AllowAnonymous]
    public class AutenticacaoController : BaseController
    {
        public AutenticacaoController(IContexto contexto)
            : base(contexto)
        {
        }

        // GET: Autenticacao
        public ActionResult Login()
        {
            string[] ufs =
            {
                "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI",
                "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO"
            };
            ViewBag.Ufs = new SelectList(ufs);
            return View(new LoginViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var autenticacao = ImplementationResolver.Resolve<IServicoAutenticacao>();

                var usuario = LoginViewModel.ToEntity(viewModel);

                /* if (autenticacao.Autenticar(usuario))
                 {*/
                var usuRepo = new UsuarioRepository(_contexto);

                var usuarioCorrente = usuRepo.ObterPorEmail(usuario.Email);
                var sessaoRepo = new SessaoRepository(_contexto, new GravadorArquivo());
                var sessao = sessaoRepo.ObterUltimaAtiva();
                usuario.Sessao = sessao;

                if (usuario.Sessao == null)
                {
                    ModelState.AddModelError("", "Nenhuma sessão está ativa");
                    return Json(
                        new
                        {
                            ValidationSummary = RenderRazorViewToString("_errosValidacao", viewModel),
                            Autenticado = false
                        }, JsonRequestBehavior.AllowGet);
                }

                FormsAuthentication.SetAuthCookie(viewModel.Email, viewModel.LembrarMe);
                var url = FormsAuthentication.GetRedirectUrl(viewModel.Email, viewModel.LembrarMe);

                if (usuarioCorrente == null)
                    usuRepo.Add(usuario);
                else
                    usuRepo.Atualizar(usuarioCorrente, usuario);
                _contexto.Salvar();
                return Json(new {Url = url, Autenticado = true}, JsonRequestBehavior.AllowGet);
                /* }
                 else
                 {
                     ModelState.AddModelError("UsuarioOuSenhaInvalidos", "Usuário ou Senha inválidos");
                 }*/
            }

            return Json(
                new {ValidationSummary = RenderRazorViewToString("_errosValidacao", viewModel), Autenticado = false},
                JsonRequestBehavior.AllowGet);
        }


        [Authorize]
        public ActionResult Sair()
        {
            QuitIrc();
            Session.Abandon();
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

Itanio.SessaoAoVivo.WebUI.Frontend/Views/Autenticacao/Login.cshtml
@using Itanio.SessaoAoVivo.Dominio
@model LoginViewModel
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Autenticacao/_Layout.cshtml";
}


<div class="card card-signup">

    @using (Html.BeginForm("Login", "Autenticacao", new {ReturnUrl = Request.QueryString["ReturnUrl"]}, FormMethod.Post, new {@class = "form", id = "frmLogin"}))
    {
        @Html.AntiForgeryToken()

        <div class="header header-primary text-center">
            <h2>Sessão Ao Vivo - @Parametro.PROJETO</h2>
            <h4>Digite seus dados para acessar</h4>
        </div>
        <div class="content">
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="material-icons">email</i>
                </span>
                <div class="form-group label-floating">
                    <label class="control-label">Digite seu email cadastrado</label>
                    @Html.TextBoxFor(x => x.Email, new {@class = "form-control", id = "txtLogin-Login"})
                </div>
            </div>
            @*<div class="input-group">
                <span class="input-group-addon">
                    <i class="material-icons">lock_outline</i>
                </span>
                <div class="form-group label-floating">
                    <label class="control-label">Digite sua senha</label>
                    @Html.EditorFor(x => x.Senha, new { HtmlAttributes = new { id = "txtLogin-Senha" } })
                </div>
            </div>*@
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="material-icons">person</i>
                </span>
                <div class="form-group label-floating">
                    <label class="control-label">Nome</label>
                    @Html.TextBoxFor(x => x.Nome, new {@class = "form-control", id = "txtLogin-Nome"})
                </div>
            </div>
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="material-icons">location_city</i>
                </span>
                <div class="form-group label-floating">
                    <label class="control-label">Cidade</label>
                    @Html.TextBoxFor(x => x.Cidade, new {@class = "form-control", id = "txtLogin-Cidade"})
                </div>
            </div>
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="material-icons">place</i>
                </span>
                <div class="form-group label-floating">
                    <label class="control-label">Estado</label>
                    @Html.DropDownListFor(model => model.Uf, ViewBag.Ufs as SelectList, " ", new {@class = "form-control dropdownjs", id = "txtLogin-Uf"})
                </div>

            </div>
            @*<div class="togglebutton text-center">
                <label>
                    @Html.CheckBoxFor(x => x.LembrarMe, new { name = "remember", id = "remember" })
                    Me Lembrar
                </label>
            </div>*@


        </div>
        <div class="footer text-center">
            <button name="login-submit" id="login-submit" class="btn btn-simple btn-primary btn-lg">Entrar</button>
        </div>

        <div id="ValidationSummaryContainer" class="container">

        </div>
    }
</div>
<div id="pre-loader-loading"></div>

@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        (function() {
            var $private = {};

            $(function() {
                $("#frmLogin").on("submit", $private.Autenticar);
            });

            $private.Autenticar = function(e) {
                e.preventDefault();
                $.validator.unobtrusive.parse($(this));

                if ($(this).valid()) {
                    var enviarTextoOriginal = $("#login-submit").text();
                    var enviando =
                        $("<img src='@Url.Content("~/Content/img/loading-green.gif")'> <span>Autenticando</span>");
                    $("#login-submit").html(enviando);
                    $("#login-submit").prop('disabled', true);
                    $.ajax({
                        url: this.action,
                        type: this.method,
                        data: $(this).serialize(),
                        success: function(result) {
                            if (result.Autenticado)
                                document.location.href = result.Url;
                            else {
                                $("#txtLogin-Login").val("");
                                $("#txtLogin-Senha").val("");
                                $("#login-submit").text(enviarTextoOriginal);
                                $("#login-submit").prop('disabled', false);
                                $("#ValidationSummaryContainer").html(result.ValidationSummary);
                            }
                        }
                    });
                }
            };
        }());
    </script>
}

Itanio.SessaoAoVivo.WebUI.Frontend/Views/Autenticacao/_Layout.cshtml
@using Itanio.SessaoAoVivo.Dominio
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <title>Sessão Ao Vivo @Parametro.PROJETO - Login</title>
    <meta http-equiv="x-ua-compatible" content="IE=10">
    <script>
        var SessaoAoVivo = {};
        SessaoAoVivo.api = '@Url.Content("~/")';
    </script>
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/csscustom")
    <link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon"/>
    <link rel="icon" href="~/favicon.ico" type="image/ico"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
    <link rel="apple-touch-icon" sizes="57x57" href="~/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="~/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="~/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="~/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="~/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="~/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="~/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="~/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="~/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="~/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="~/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/favicon-16x16.png">
    <link rel="manifest" href="~/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="~/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
</head>
<body class="signup-page">
<div class="wrapper">
    <div class="header header-filter" style="background-image: url('https://i.ytimg.com/vi/s-8-c5O5C1g/maxresdefault.jpg'); background-position: top center; background-size: cover;">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    @RenderBody()
                </div>
            </div>

            <footer class="footer">
                <div class="container">
                    <nav class="pull-left">
                        <ul>
                            <li>
                                Sessão Ao Vivo
                            </li>
                        </ul>
                    </nav>
                    <div class="copyright pull-right">
                        © 2016, feito com <i class="fa fa-heart heart"></i> por <a href="http://www.itanio.com.br" target="_blank">Itanio</a>
                    </div>
                </div>
            </footer>
        </div>
    </div>
</div>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@Html.Partial("_Alert")
@RenderSection("scripts", false)
</body>
</html>